version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - node1
      - node2
      - node3

  node1:
    build: ./node
    ports:
      - "8081:8080"  # Explicitly map the host and container ports
    depends_on:
      - redis

  node2:
    build: ./node
    ports:
      - "8082:8080"  # Explicitly map the host and container ports
    depends_on:
      - redis

  node3:
    build: ./node
    ports:
      - "8083:8080"  # Explicitly map the host and container ports
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"  # Explicitly map the host and container ports
